### ISSUE TITLE
input image가 제대로 출력 안됨

### ISSUE THREAD

**Issue by greatgucci** [OSS-2021-team3/Drawing-Trade#7]
![image](https://user-images.githubusercontent.com/32212074/120912181-1dc2da00-c6c8-11eb-8e01-38a399ae103c.png)

**Comment by greatgucci** [comment]
![graph3](https://user-images.githubusercontent.com/32212074/120912202-48149780-c6c8-11eb-8c4e-2f25d19dad92.png)

**Comment by DogRing** [comment]
원본이미지를 resize하지 않고 그대로 올려 잘리는 현상이 발생

**Comment by Kapurichino** [comment]
이미지를 resize 하는 것은 mvp에서 구현하지 않고, 추가 구현 계획에서 진행할 예정입니다. 
지금은 350 * 200 정도의 사이즈로 이미지를 그려서 test해보시길 바랍니다.
